# Generated by Django 5.2.9 on 2026-01-12 12:04

import booklandapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0023_alter_feestructure_meals_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnimessage',
            name='year_of_completion',
            field=models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=booklandapp.models.current_year),
        ),
    ]
