# Generated by Django 5.2.9 on 2026-01-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0024_alter_alumnimessage_year_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipmessage',
            name='rank',
            field=models.PositiveIntegerField(default=999, help_text='Lower number = higher rank'),
        ),
    ]
