# Generated by Django 5.2.9 on 2026-01-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0025_leadershipmessage_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadershipmessage',
            name='rank',
        ),
    ]
