# Generated by Django 5.2.9 on 2026-02-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0026_remove_leadershipmessage_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='meals_fee',
            new_name='tuition_term_One',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='transport_fee',
            new_name='tuition_term_Three',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_per_term',
            new_name='tuition_term_Two',
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='level',
            field=models.CharField(choices=[('Play Group', 'Play Group'), ('PP1', 'PP1'), ('PP2', 'PP2'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=50, unique=True),
        ),
    ]
