# Generated by Django 5.2.9 on 2026-02-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0027_rename_meals_fee_feestructure_tuition_term_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_term_One',
            new_name='meals_fee',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_term_Three',
            new_name='transport_fee',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_term_Two',
            new_name='tuition_per_term',
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='level',
            field=models.CharField(choices=[('Play Group', 'Play Group'), ('PP1 - PP2', 'PP1 - PP2'), ('Grade 1 - 3', 'Grade 1 - 3'), ('Grade 4 - 6', 'Grade 4 - 6'), ('Junior Secondary', 'Junior Secondary')], max_length=50, unique=True),
        ),
    ]
