# Generated by Django 5.2.9 on 2026-02-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0028_rename_tuition_term_one_feestructure_meals_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='meals_fee',
            new_name='total_tuition_fee',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='total_fee',
            new_name='tuition_fee_term1',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='transport_fee',
            new_name='tuition_fee_term2',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_per_term',
            new_name='tuition_fee_term3',
        ),
    ]
