# Generated by Django 5.2.9 on 2026-02-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0029_rename_meals_fee_feestructure_total_tuition_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_fee_term1',
            new_name='tuition_fee_term_One',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_fee_term2',
            new_name='tuition_fee_term_Three',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_fee_term3',
            new_name='tuition_fee_term_Two',
        ),
    ]
