# Generated by Django 5.2.9 on 2026-02-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0030_rename_tuition_fee_term1_feestructure_tuition_fee_term_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_fee_term_Two',
            new_name='tuition_fee_term_1',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_fee_term_One',
            new_name='tuition_fee_term_2',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_fee_term_Three',
            new_name='tuition_fee_term_3',
        ),
    ]
