# Generated by Django 5.2.9 on 2026-02-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklandapp', '0031_rename_tuition_fee_term_two_feestructure_tuition_fee_term_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='level',
            field=models.CharField(choices=[('Play Group', 'Play Group'), ('PP1', 'PP1'), ('PP2', 'PP2'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=50, unique=True),
        ),
    ]
